### PR TITLE
Feature/udpate ruby version

### PR DESCRIPTION
**Pull request by ferndopolis**
update to gems and ruby

### CODE REVIEW

**Comment by michaelkirk** [comment]
specs pass, but cucumbers failed.

```
(::) failed steps (::)

undefined method `FactoryGirl' for #<Cucumber::Rails::World:0x007f1dc1cbb958> (NoMethodError)
./features/step_definitions/household_steps.rb:33:in `block (2 levels) in <top (required)>'
./features/step_definitions/household_steps.rb:31:in `map'
./features/step_definitions/household_steps.rb:31:in `/^a household with "([^"]*)" as a? ?members?$/'
features/create_member.feature:22:in `Given a household with "Jared Noem" as a member'

undefined method `FactoryGirl' for #<Cucumber::Rails::World:0x007f1dc1f32b28> (NoMethodError)
./features/step_definitions/household_steps.rb:33:in `block (2 levels) in <top (required)>'
./features/step_definitions/household_steps.rb:31:in `map'
./features/step_definitions/household_steps.rb:31:in `/^a household with "([^"]*)" as a? ?members?$/'
features/search_households.feature:9:in `And a household with "Tye Johnson and Jared Noem" as members'

undefined method `FactoryGirl' for #<Cucumber::Rails::World:0x007f1dbf98b258> (NoMethodError)
./features/step_definitions/accounting_steps.rb:16:in `/^that household spent \$(\d+) over a week ago$/'
features/weekly_throughput.feature:21:in `Given that household spent $20 over a week ago'

Failing Scenarios:
cucumber features/create_member.feature:21 # Scenario: add member to household
cucumber features/search_households.feature:13 # Scenario: search with first name
cucumber features/weekly_throughput.feature:20 # Scenario: Don't count sales from last week
```

**Comment by ferndopolis** [comment]
@michaelkirk missed a few check now, it's been awhile using cukes

**Comment by michaelkirk** [comment]
added a couple of things.

Also, I can no longer log in with the same username/password. Did upgrading devise break existing passwords?

**Comment by michaelkirk** [comment]
(tests passing btw! :thumbsup: )

**Pull request merged**
